// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ticketing.Query.Infrastructure.Persistence;

#nullable disable

namespace Ticketing.Query.Infrastructure.Persistence.Migations
{
    [DbContext(typeof(TicketDbContext))]
    partial class TicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ticketing.Query.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Ticketing.Query.Domain.TicketTypes.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TicketTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FatalEror"
                        },
                        new
                        {
                            Id = 2,
                            Name = "WarningError"
                        },
                        new
                        {
                            Id = 3,
                            Name = "NotFoundDeviceError"
                        },
                        new
                        {
                            Id = 4,
                            Name = "InternalDeviceEror"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ManagePersonError"
                        });
                });

            modelBuilder.Entity("Ticketing.Query.Domain.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TicketType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("Ticketing.Query.Domain.Tickets.TicketEmployee", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmploteeId")
                        .HasColumnType("uuid");

                    b.HasKey("TicketId", "EmploteeId");

                    b.HasIndex("EmploteeId");

                    b.ToTable("TicketEmployees", (string)null);
                });

            modelBuilder.Entity("Ticketing.Query.Domain.Employees.Employee", b =>
                {
                    b.OwnsOne("Ticketing.Query.Domain.Adresses.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .HasColumnType("text");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Ticketing.Query.Domain.Tickets.TicketEmployee", b =>
                {
                    b.HasOne("Ticketing.Query.Domain.Employees.Employee", "Employee")
                        .WithMany("TicketEmployees")
                        .HasForeignKey("EmploteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketing.Query.Domain.Tickets.Ticket", "Ticket")
                        .WithMany("TicketEmployees")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Ticketing.Query.Domain.Employees.Employee", b =>
                {
                    b.Navigation("TicketEmployees");
                });

            modelBuilder.Entity("Ticketing.Query.Domain.Tickets.Ticket", b =>
                {
                    b.Navigation("TicketEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
